### ISSUE TITLE
Error: couldn't retrieve IP address of domain

### ISSUE THREAD

**Issue by MarkYSA** [MusicDin/kubitect#149]
Hi,

I'm using default NAT sample config and receive such error during setup

╷
│ Error: couldn't retrieve IP address of domain id: 02bcae0c-2ceb-4658-aa88-36746361bd65. Please check following:
│ 1) is the domain running proplerly?
│ 2) has the network interface an IP address?
│ 3) Networking issues on your libvirt setup?
│  4) is DHCP enabled on this Domain's network?
│ 5) if you use bridge network, the domain should have the pkg qemu-agent installed
│ IMPORTANT: This error is not a terraform libvirt-provider error, but an error caused by your KVM/libvirt infrastructure configuration/setup
│  timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)
│
│   with module.host_localhost.module.master_module["1"].libvirt_domain.vm_domain,
│   on modules/vm/vm.tf line 72, in resource "libvirt_domain" "vm_domain":
│   72: resource "libvirt_domain" "vm_domain" {
│
╵
┌
│ Error: terraform apply failed: exit status 1

But host is accessible via IP:

root@###:~/kubitect# ping 192.168.113.10
PING 192.168.113.10 (192.168.113.10) 56(84) bytes of data.
64 bytes from 192.168.113.10: icmp_seq=1 ttl=64 time=0.301 ms

I have Debian 12

**Comment by MusicDin** [comment]
Hi @MarkYSA,

that is really odd. I was not able to reproduce the issue, but ran into the similar issue with CentOS Stream 9. Could you please provide the Kubitect config file?

**Comment by MarkYSA** [comment]
@MusicDin Thank you for you reply!

Sure, here is it:

hosts:
  - name: localhost
    connection:
      type: local

cluster:
  name: k8s-cluster
  network:
    mode: nat
    cidr: 192.168.113.0/24
    dhcp:
      enabled: false
  nodeTemplate:
    user: k8s
    updateOnBoot: false
    ssh:
      addToKnownHosts: true
    os:
      distro: ubuntu22
  nodes:
    master:
      default:
        ram: 6
        cpu: 4
        mainDiskSize: 20
      instances:
        - id: 1
          ip: 192.168.113.10

kubernetes:
  version: v1.26.6
  networkPlugin: calico

**Comment by MusicDin** [comment]
Hi @MarkYSA, thanks for providing the configuration file. 

I can confirm that when static IP addresses are set in NAT mode, it causes libvirt not to register them, which produces the above issue.

**Comment by MusicDin** [comment]
Hi @MarkYSA,

This has been fixed in `[v3.2.1](https://github.com/MusicDin/kubitect/releases/tag/v3.2.1)`. Let me know if you encounter any other issue.
