### ISSUE TITLE
Terraform Proxy For AirGap Environments

### ISSUE THREAD

**Issue by mjekrami** [MusicDin/kubitect#190]
I've added the feature to pass `HTTPS_PROXY` env variable to the terraform process but i don't know how to make a pull request (push my code) to the repo. I've created a branch called `feat/terraform-proxy` but i'm unable to push it.

Thanks for this awesome project BTW

**Comment by MusicDin** [comment]
Hi, I'm glad you found the project useful :)

To contribute the code, first you need to fork the project and then push the code to your own fork (can be any branch).

Afterwards, go to the `Pull Requests` tab -> `New Pull Request` -> and there should be a button *compare across forks* -> select your fork and the desired branch (that you want to merge).

Usually GitHub also gives you a popup to open a pull request when you push code to the forked repository.

Let me know if you need any further assistance or have any other questions.

**Comment by MusicDin** [comment]
Closing this in favor of https://github.com/MusicDin/kubitect/pull/191
