### ISSUE TITLE
Asset for linux/arm64 isn't found in kubitect v2.0.7

### ISSUE THREAD

**Issue by suzuki-shunsuke** [MusicDin/kubitect#22]
Thank you for your great project.

I found that there is no asset for linux/arm64 in the latest release v2.0.7.

https://github.com/MusicDin/kubitect/releases/tag/v2.0.7

<img width="462" alt="image" src="https://user-images.githubusercontent.com/13323303/173210501-62e9bf78-c5df-4a36-862d-a47cd7bf462c.png">

On the other hand, there is the asset for linux/arm64 in the previous release v2.0.6.

https://github.com/MusicDin/kubitect/releases/tag/v2.0.6

<img width="420" alt="image" src="https://user-images.githubusercontent.com/13323303/173210512-4e4c1d01-ead2-4a4d-980e-bc42e05726e1.png">

Could you release the asset for linux/arm64?

## Reference

* https://github.com/aquaproj/aqua-registry/pull/3933
* https://github.com/aquaproj/aqua-registry/pull/3673

**Comment by suzuki-shunsuke** [comment]
If you won't release assets for linux/arm64, please close this issue.

**Comment by MusicDin** [comment]
Hi,

thanks for opening the issue, I have updated the assets.
Please let me if there will be any issues on arm64 arch.

**Comment by suzuki-shunsuke** [comment]
Thank you for your quick update!
I've confirmed I can run kubitect on linux/arm64.

```console
$ kubitect -v
kubitect version v2.0.7
```
