### ISSUE TITLE
Support adding taints to kubernetes nodes

### ISSUE THREAD

**Issue by seumasdunlop** [MusicDin/kubitect#23]
In the same way that labels can be added to kubernetes nodes it would be useful to add taints from the template.

I've implemented this so let me know if you're happy for a pull request.

**Comment by MusicDin** [comment]
Hi,

first of all, thank you for opening all these issues.

Taints should definitely be added, so I would really appreciate, if you could open a pull request.

**Comment by seumasdunlop** [comment]
You're welcome, thanks for the great project :)  I've created a pull request for this.
