### ISSUE TITLE
Using 'resolvconf_mode: docker_dns' not working with containerd 

### ISSUE THREAD

**Issue by seumasdunlop** [MusicDin/kubitect#24]
I had to change the `resolvconf_mode `to `host_resolvconf ` to get DNS resolution to work because docker didn't exist.  This matches the current kubespray upstream [defaults](https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml#L195).

**Comment by MusicDin** [comment]
Thanks for reporting this issue, could you please open a pull request for this?
