### ISSUE TITLE
Unable to create bridge based build - missing qemu-guest-agent pkg

### ISSUE THREAD

**Issue by fischerdr** [MusicDin/kubitect#63]
All,
when is try and create a build with network mode bridge i always get the following
Error: couldn't retrieve IP address of domain id: 419fd838-2aa4-4c58-b6fe-b39c4216172d. Please check following: 
1) is the domain running proplerly? 
2) has the network interface an IP address? 
3) Networking issues on your libvirt setup? 
 4) is DHCP enabled on this Domain's network? 
5) if you use bridge network, the domain should have the pkg qemu-agent installed 
IMPORTANT: This error is not a terraform libvirt-provider error, but an error caused by your KVM/libvirt infrastructure configuration/setup 
 invalid argument

  with module.host_localhost.module.worker_module["2"].libvirt_domain.vm_domain,
  on modules/vm/vm.tf line 73, in resource "libvirt_domain" "vm_domain":
  73: resource "libvirt_domain" "vm_domain" {

I have loged into the created vm and see the the pkg qemu-guest-agent is missing.
For the os i am using the default which is 
[kubitect-br.yaml.gz](https://github.com/MusicDin/kubitect/files/9485293/kubitect-br.yaml.gz)
ubuntu22
attached is the yaml i am using

**Comment by fischerdr** [comment]
example
ssh -i ~/.ssh/id_k8s k8s@192.168.101.10
The authenticity of host '192.168.101.10 (192.168.101.10)' can't be established.
ED25519 key fingerprint is SHA256:jSG7MxGdyQ5V4vZwJcMmBVmslrCm08+kWsN/VK5xOw8.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.101.10' (ED25519) to the list of known hosts.
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-125-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sun Sep  4 18:53:24 UTC 2022

  System load:  0.52              Processes:             128
  Usage of /:   4.4% of 30.83GB   Users logged in:       0
  Memory usage: 5%                IPv4 address for ens3: 192.168.101.10
  Swap usage:   0%

0 updates can be applied immediately.


The list of available updates is more than a week old.
To check for new updates run: sudo apt update


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

k8s@k8s-cluster-master-1:~$ sudo su -
root@k8s-cluster-master-1:~# apt-cache show qemu-guest-agent
N: Unable to locate package qemu-guest-agent
E: No packages found

**Comment by MusicDin** [comment]
First of all, thanks for opening an issue.

To me this seems lika a DNS problem. Could you please paste the output of the `resolvectl` command from your virtual machine (`k8s-cluster-master-1`)?

Example output:
```
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (ens3)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 8.8.8.8
       DNS Servers: 8.8.8.8 1.1.1.1
```

In addition, you can try to set the dns property in nodeTemplate:
```yaml
cluster:
  nodeTemplate:
    dns:
      - 8.8.8.8 # Google's DNS
      - 1.1.1.1 # Cloudflare's DNS
```

**Comment by fischerdr** [comment]
First Thanks for the quick response.  Your suggestion help me find that my vlan router lost its primary gateway route.
Once I had the route up I was able to bring the whole build online.
Thanks again
